### ISSUE TITLE
Create `/login` endpoint

### ISSUE THREAD

**Issue by jeremygarey** [jeremygarey/ride-share#1]
I think we need a `/login` endpoint. We need a way to know which user is logged in so that we can associate that user with a ride when they select one.

I think we can implement it in pretty much the exact same way as it is here: https://github.com/tu-cos-243/ui-spa/blob/a134c430b1a4bc1fc4bc8dd416e87d7bd0c39419/hapi-server.js

We would just use `user` instead of `account` and some other small differences.

**Comment by phinneyn** [comment]
Added the `/login` endpoint. All is bueno.
